### PR TITLE
Fix winget installer regex

### PR DESCRIPTION
**Pull request by sitiom**
Try rereleasing afterwards (or convert to draft and undraft might trigger the workflow again?)

### CODE REVIEW

**Comment by sitiom** [comment]
@xmine64

**Comment by sitiom** [comment]
@xmine64 Updates on releasing to Winget?

**Comment by xmine64** [comment]
> Updates on releasing to Winget?

I'll try soon

**Comment by sitiom** [comment]
Make sure to move the tag to the latest commit before doing so.

**Comment by xmine64** [comment]
Ok Now working: https://github.com/microsoft/winget-pkgs/pull/77642

I had to create a new release, it's not possible to convert a published release to draft again

**Comment by sitiom** [comment]
> I had to create a new release, it's not possible to convert a published release to draft again

It is possible:
image

**Comment by sitiom** [comment]
@xmine64 Please apply my suggestion in https://github.com/microsoft/winget-pkgs/pull/77642#discussion_r961587662

**Comment by xmine64** [comment]
> It is possible

I couldn't find that button, it's done btw

**Pull request merged**
