### PR TITLE
Simplify build and release workflow

### PR DESCRIPTION
**Pull request by sitiom**
- Combine `build.yml` and `release.yml` as separate jobs in `ci.yml` so that the `build.yml` code is not duplicated
- Remove unnecessary variable assignments
- Use https://github.com/battila7/get-version-action to get the current tag action
- Build all, then create a draft release using https://github.com/softprops/action-gh-release. You then have to publish it yourself manually. Resolves https://github.com/MicaForEveryone/MicaForEveryone/pull/102#issuecomment-1198254716.
- `iscc` is already in the PATH, do not call directly to its absolute path. Also, build the installer to `RELEASE_DIR`.
- Add [Dependabot](https://github.com/dependabot) to automatically update dependencies

Everything is tested to be working as intended in [my fork](https://github.com/sitiom/MicaForEveryone/).

### CODE REVIEW

**Comment by xmine64** [comment]
Nice work, thanks

**Comment by sitiom** [comment]
@xmine64 bump

**Comment by xmine64** [comment]
Build failed but I merge anyway, will fix if it still fails later.

**Comment by sitiom** [comment]
I think the installer regex is wrong, will fix.

**Comment by sitiom** [comment]
@xmine64 Please try drafting and undrafting the current release to trigger the Winget workflow again.

**Comment by sitiom** [comment]
@xmine64 I forgot an extra step: You should keep the fork regularly updated with [Pull](https://github.com/apps/pull). Otherwise, it will eventually try to update the old workflows without the `workflow` scope, resulting in an error.

**Pull request merged**
