### PR TITLE
Support for setting corner preference

### PR DESCRIPTION
**Pull request by krlvm**
This will allow to set corner preference on build 22000 and higher using the [DwmSetWindowAttribute](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute) API with [DWMWA_WINDOW_CORNER_PREFERENCE](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute) as attribute and [DWM_WINDOW_CORNER_PREFERENCE](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_window_corner_preference) as value.

### CODE REVIEW

**Comment by xmine64** [comment]
Seems easy, a v1.1.0.0 is coming

**Comment by dongle-the-gadget** [comment]
We would need translators though

**Comment by krlvm** [comment]
Updated Russian translation in general and translated the new strings.
Also need to pick an Segoe UI MDL2 Assets icon for this option.

**Comment by dongle-the-gadget** [comment]
Remove line 17 (`SymbolThemeFontFamily`) in `App.xaml`?

**Comment by krlvm** [comment]
> Remove line 17 (`SymbolThemeFontFamily`) in `App.xaml`?

Oh, I meant `Segoe Fluent Icons`, not `Segoe UI MDL2 Assets`

**Comment by krlvm** [comment]
> Remove line 17 (`SymbolThemeFontFamily`) in `App.xaml`?

After I've removed this line, also properly shows icons on Windows 10, including tray icon menu:
image

**Comment by dongle-the-gadget** [comment]
Wait somehow Visual Studio messed up and created a `corner_preference` branch lol.

**Comment by xmine64** [comment]
Translate these:
@xoascf @Danik2343 @maboroshin @alessandrocaseti @uDEV2019 @AndromedaMelody @SaiyajinK

```xml
  <data name="CornerMenu.Text" xml:space="preserve">
    <value>Corner Mode</value>
  </data>
  <data name="CornerPreferenceSetting.Header" xml:space="preserve">
    <value>Corner Mode</value>
  </data>
  <data name="SquareMenuItem.Text" xml:space="preserve">
    <value>Square</value>
  </data>
  <data name="RoundedMenuItem.Text" xml:space="preserve">
    <value>Rounded</value>
  </data>
  <data name="RoundedSmallMenuItem.Text" xml:space="preserve">
    <value>Slightly Rounded</value>
  </data>
  <data name="CornerDescription.Text" xml:space="preserve">
    <value>Set corner rounding mode,</value>
  </data>
  <data name="DefaultCornerDescription.Text" xml:space="preserve">
    <value>Default doesn't do anything to keep app's preferred corner rounding mode.</value>
  </data>
  <data name="SquareCornerDescription.Text" xml:space="preserve">
    <value>Square mode disables corner rounding.</value>
  </data>
  <data name="RoundedCornerDescription.Text" xml:space="preserve">
    <value>Rounded mode enables rounded corners by force.</value>
  </data>
  <data name="RoundedSmallCornerDescription.Text" xml:space="preserve">
    <value>Slightly rounded mode is in the middle between square and rounded corners.</value>
  </data>
```

**Review by xmine64 — COMMENTED** [review]
I'm gonna revert this commit, I prefer embedding Segoe Fluent Icons in app instead of using MDL2 font on Windows 10.

**Comment by dongle-the-gadget** [comment]
It makes thing look kinda off, I would say.

**Comment by xmine64** [comment]
You can see it's using wrong icon:

image

**Comment by dongle-the-gadget** [comment]
How about E179?

**Comment by xmine64** [comment]
> How about E179?

We would need separate icons for Windows 10 and Windows 11. Let's just embed Segoe Fluent Icons in app but not in this PR.

**Comment by dongle-the-gadget** [comment]
That would still require a modification to the `App.xaml` file though.

**Comment by Danik2343** [comment]
` <data name="CornerMenu.Text" xml:space="preserve">
    <value>Угловой режим</value>
  </data>
  <data name="CornerPreferenceSetting.Header" xml:space="preserve">
    <value>Угловой режим</value>
  </data>
  <data name="SquareMenuItem.Text" xml:space="preserve">
    <value>Квадрат</value>
  </data>
  <data name="RoundedMenuItem.Text" xml:space="preserve">
    <value>Закругленный</value>
  </data>
  <data name="RoundedSmallMenuItem.Text" xml:space="preserve">
    <value>Слегка закругленный</value>
  </data>
  <data name="CornerDescription.Text" xml:space="preserve">
    <value>Установите режим скругления углов,</value>
  </data>
  <data name="DefaultCornerDescription.Text" xml:space="preserve">
    <value>По умолчанию ничего не делается для сохранения предпочтительного режима скругления углов приложения.</value>
  </data>
  <data name="SquareCornerDescription.Text" xml:space="preserve">
    <value>Квадратный режим отключает скругление углов.</value>
  </data>
  <data name="RoundedCornerDescription.Text" xml:space="preserve">
    <value>Закругленный режим позволяет принудительно скруглять углы.</value>
  </data>
  <data name="RoundedSmallCornerDescription.Text" xml:space="preserve">
    <value>Слегка закругленный режим находится посередине между квадратными и закругленными углами.</value>
  </data>`

**Comment by Danik2343** [comment]
[ru-ru.txt](https://github.com/MicaForEveryone/MicaForEveryone/files/9028741/ru-ru.txt)

**Comment by krlvm** [comment]
I have already translated the new strings to Russian

**Comment by SaiyajinK** [comment]
Hi,
Of course:

------------------------------------------------






























*  <data name="CornerMenu.Text" xml:space="preserve">
<value>Personnalisation des coins</value>  </data>  <data
name="CornerPreferenceSetting.Header" xml:space="preserve">
<value>Personnalisation des coins</value>  </data>  <data
name="SquareMenuItem.Text" xml:space="preserve">    <value>Carré</value>
</data>  <data name="RoundedMenuItem.Text" xml:space="preserve">
<value>Arrondi</value>  </data>  <data name="RoundedSmallMenuItem.Text"
xml:space="preserve">    <value>Légèrement arrondi</value>  </data>  <data
name="CornerDescription.Text" xml:space="preserve">    <value>Définir le
mode arrondi des coins,</value>  </data>  <data
name="DefaultCornerDescription.Text" xml:space="preserve">
<value>"Défaut" ne conserve pas le mode arrondi des coins préféré dans
l'application.</value>  </data>  <data name="SquareCornerDescription.Text"
xml:space="preserve">    <value>"Carré" désactive l'arrondi des
coins.</value>  </data>  <data name="RoundedCornerDescription.Text"
xml:space="preserve">    <value>"Arrondi" force l'activation des coins
arrondis.</value>  </data>  <data name="RoundedSmallCornerDescription.Text"
xml:space="preserve">    <value>"légèrement arrondi" active les coins
semi-arrondis.</value>  </data>*

------------------------------------------------

a small question: if in the future I want to propose an update of my
translation, how should I go about sending it to you? directly by email? or
by opening a "ticket" on the Mica GitHub repository?

thanks for your answer ++

Le ven. 1 juil. 2022 à 12:14, Mohammad Amin ***@***.***> a
écrit :

**Pull request merged**
