### PR TITLE
Allow system-wide installation of innosetup installer

### PR DESCRIPTION
**Pull request by sitiom**
Some would want to have MicaForEveryone installed system-wide:
image

### CODE REVIEW

**Comment by xmine64** [comment]
I tried this first but it breaks `/S` parameter support that's needed to install silently with winget.

**Comment by sitiom** [comment]
> I tried this first but it breaks `/S` parameter support that's needed to install silently with winget.

You need to pass `/ALLUSERS` or `/CURRENTUSER` for it to work. See [Setup Command Line Parameters](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline):

> **/ALLUSERS**
> Instructs Setup to install in [administrative install](https://jrsoftware.org/ishelp/topic_admininstallmode.htm) mode. Only has an effect when the [Setup] section directive [PrivilegesRequiredOverridesAllowed](https://jrsoftware.org/ishelp/topic_setup_privilegesrequiredoverridesallowed.htm) allows the commandline override.

> 
> **/CURRENTUSER**
> Instructs Setup to install in [non administrative install](https://jrsoftware.org/ishelp/topic_admininstallmode.htm) mode. Only has an effect when the [Setup] section directive [PrivilegesRequiredOverridesAllowed](https://jrsoftware.org/ishelp/topic_setup_privilegesrequiredoverridesallowed.htm) allows the commandline override.

**Comment by xmine64** [comment]
> You need to pass /ALLUSERS or /CURRENTUSER for it to work.

Ok, thanks. Did you do it in your #102?

**Comment by sitiom** [comment]
No. The action only uses [`YamlCreate.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) to update the installer links to the new versions. A PR must be created to fix it (use the one that will be created from the action when you make a new release).

**Comment by xmine64** [comment]
We need to be able add custom fields to manifest to make it work, but it is not possible using winget-releaser.

**Comment by sitiom** [comment]
> We need to be able add custom fields to manifest to make it work, but it is not possible using winget-releaser.

Winget releaser just updates the links, you can directly PR to winget-pkgs.

**Comment by xmine64** [comment]
> Winget releaser just updates the links, you can directly PR to winget-pkgs for that.

Cool, then I'll do it soon.

**Comment by sitiom** [comment]
> > Winget releaser just updates the links, you can directly PR to winget-pkgs for that.
> 
> Cool, then I'll do it soon.

You can include the change in the PR that winget releaser will generate in the next release.

**Comment by sitiom** [comment]
@xmine64 Just a note, I'm currently adding additional information on the current MicaForEveryone package (https://github.com/microsoft/winget-pkgs/pull/67360). In my experience, [YAMLCreate.ps1](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#using-the-yamlcreateps1) is better than [wingetcreate](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#using-wingetcreate-utility) in creating packages, which is what this action is also using.

**Comment by sitiom** [comment]
> @xmine64 Just a note, I'm currently adding additional information on the current MicaForEveryone package ([microsoft/winget-pkgs#67360](https://github.com/microsoft/winget-pkgs/pull/67360)). In my experience, [YAMLCreate.ps1](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#using-the-yamlcreateps1) is better than [wingetcreate](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#using-wingetcreate-utility) in creating packages, which is what the winget releaser action is also using.

Done. Can you merge this now?

**Pull request merged**
