### PR TITLE
Add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).

example

2. Fork https://github.com/microsoft/winget-pkgs under @MicaForEveryone. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Make sure the PAT owner has signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the source code is [here](https://github.com/vedantmgoyal2009/winget-releaser).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/issues (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/issues?q=Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@xmine64 you need to publish releases using a personal access token (PAT) since when the release is published by github-actions:

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "[Authenticating with the GITHUB_TOKEN](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)."

_Source: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow_

This won't trigger the winget workflow: 
image

**Comment by sitiom** [comment]
@vedantmgoyal2009 https://github.com/PolyMC/PolyMC uses the GitHub token to create releases, and Winget Releaser works. What's the difference with this one?

**Comment by xmine64** [comment]
> For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

Makes sense, thanks to mention that. I'll test for next release and if it didn't work I'll merge winget releaser workflow and publish workflow.

**Comment by vedantmgoyal2009** [comment]
PolyMC have draft releases initially and they are published manually. But here, I suppose it is being published directly.

**Comment by sitiom** [comment]
Oh ok, how about https://github.com/neovim/neovim? They don't do draft releases, do they?

**Comment by vedantmgoyal2009** [comment]
I wasn't able to understand their workflow but I'll keep watching the next release to see of it works or not.

**Comment by sitiom** [comment]
The relevant code is [here](https://github.com/neovim/neovim/blob/e59bc078de624a5f3220bfd2713be3f8978c5672/.github/workflows/release.yml#L224-L229). `gh release create` is used to create a release and the `--draft` flag is not specified.

**Comment by sitiom** [comment]
> > For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
> 
> Makes sense, thanks to mention that. I'll test for next release and if it didn't work I'll merge winget releaser workflow and publish workflow.

@xmine64 Please see #112

**Pull request merged**
